apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created
  #in the Kubernetes cluster
  name: creswave-code-test-service
spec:
  selector:
    app: creswave-code-test
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 3326 #Service port
      targetPort: 3326